title: Crimsonian
authors: Crimson MacDonald and Laurie Sharp-Page
author_link: http://crimsonian.com/about
author_description: Two ladies, two microphones and a bottle of wine.
email: crimson.macdonald@gmail.com
description: crimsonian.com is a happy-hour style podcast, where we discuss the most interesting and compelling stories of the week.
baseurl: ""
url: "http://crimsonian.com"
picturefill: false
typekit_kit_id: kwf5dox

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
paginate: 5
markdown: kramdown
permalink: pretty
sass:
  style: :compressed

collections:
  my_categories:
    output: true
    permalink: /category/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category
